from typing import Any

class CP_CODE_MANAGER:
    def GetStockListByMarket(self, type: int) -> list[str]: ...

class CP_STOCK_CHART:
    def SetInputValue(self, type: int, value: Any) -> None: ...
    def GetHeaderValue(self, type: int) -> Any: ...
    def GetDataValue(self, type: int, index: int) -> Any: ...
